export const abs = [
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/J3xGdy=uGEyk7X',
    id: '0001',
    name: '3/4 sit-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/chth9xKBboueTR',
    id: '0002',
    name: '45° side bend',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/=e28lxZqUF6tQo',
    id: '0003',
    name: 'air bike',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/HY04ZjqdXM6-gF',
    id: '0006',
    name: 'alternate heel touchers',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/BVUjNPKMbP7_=_',
    id: '2355',
    name: 'arm slingers hanging bent knee legs',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/JHEP9POLO8nP=s',
    id: '2333',
    name: 'arm slingers hanging straight legs',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/jcYtnMU0=7i-Wb',
    id: '3204',
    name: 'arms overhead full sit-up (male)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/m=iG+xt2ZA5Mu6',
    id: '0011',
    name: 'assisted hanging knee raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/Yp1YKcY7egULKr',
    id: '0010',
    name: 'assisted hanging knee raise with throw down',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/mVOtJhaXMNlb8+',
    id: '0012',
    name: 'assisted lying leg raise with lateral throw down',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/nIoXgzyuvEfj8c',
    id: '0013',
    name: 'assisted lying leg raise with throw down',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'medicine ball',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/5G51fsT_fUIazo',
    id: '0014',
    name: 'assisted motion russian twist',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/LC2-9GXtwo-ix_',
    id: '1714',
    name: 'assisted prone rectus femoris stretch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/eqDo_Djgh9W0Mw',
    id: '1758',
    name: 'assisted sit-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/9KvDtdFnv5JJQ4',
    id: '0969',
    name: 'band alternating v-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/DQLuESswxwEhm0',
    id: '0971',
    name: 'band assisted wheel rollerout',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/m3DGRbn4mj_Iz_',
    id: '0972',
    name: 'band bicycle crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/oQNqt1glFOvc7i',
    id: '0979',
    name: 'band horizontal pallof press',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/_=kcFeQYCIKJM-',
    id: '0981',
    name: 'band jack knife sit-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/wrLc-rx2-VNz_b',
    id: '0985',
    name: 'band kneeling twisting crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/qF7W+aAxzaTL2D',
    id: '1002',
    name: 'band lying straight leg raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/dR-6irUa300CLA',
    id: '0992',
    name: 'band push sit-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/vh3bPHEPiXtp-D',
    id: '1011',
    name: 'band seated twist',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/N55qFnDsBST4X3',
    id: '1005',
    name: 'band standing crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/miUIdwmOYZ3upr',
    id: '1007',
    name: 'band standing twisting crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/ldSizwkABVrH4p',
    id: '1014',
    name: 'band v-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/UkiA+HjZG1hSb0',
    id: '1015',
    name: 'band vertical pallof press',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'barbell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/qyaV4AC3+hRUZs',
    id: '0071',
    name: 'barbell press sit-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'barbell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/xoQUsdXULN42mz',
    id: '0084',
    name: 'barbell rollerout',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'barbell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/Su5BjiksjI=JJu',
    id: '0083',
    name: 'barbell rollerout from bench',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'barbell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/ExupftdHQqFEOD',
    id: '0094',
    name: 'barbell seated twist',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'barbell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/M7cHFmxoYrfNV6',
    id: '0096',
    name: 'barbell side bent v. 2',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'barbell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/noriPMIbhN-UGZ',
    id: '2799',
    name: 'barbell sitted alternate leg raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'barbell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/uQSbN6caOAdqS8',
    id: '2800',
    name: 'barbell sitted alternate leg raise (female)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'barbell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/3G-Mcbq_sUikiU',
    id: '0103',
    name: 'barbell standing ab rollerout',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'barbell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/SgAMnVN+5a9pkt',
    id: '0112',
    name: 'barbell standing twist',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/lKolzUsb8zSybK',
    id: '3544',
    name: 'bodyweight incline side plank',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/gbKH_qfrAuppcX',
    id: '0138',
    name: 'bottoms-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/rQuoPwtEuI1XVS',
    id: '2466',
    name: 'bridge - mountain climber (cross body)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/yOhkIgUUdNgoH-',
    id: '0870',
    name: 'butt-ups',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/KPf4oRS-hQ-d5m',
    id: '0174',
    name: 'cable judo flip',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/IgJ8OGhLvoH2xY',
    id: '0175',
    name: 'cable kneeling crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/65PidmAknjCho4',
    id: '0873',
    name: 'cable reverse crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/ws8LW4Byz+WeMe',
    id: '0211',
    name: 'cable russian twists (on stability ball)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/IX6Zd=Mue9u-2M',
    id: '0212',
    name: 'cable seated crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/HWx81fsFnM39DI',
    id: '2399',
    name: 'cable seated twist',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/oBv2smVlwqHwmf',
    id: '0222',
    name: 'cable side bend',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/hZE1Rmj7XQEGOs',
    id: '0221',
    name: 'cable side bend crunch (bosu ball)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/AE4BDRQcq0-k7g',
    id: '0223',
    name: 'cable side crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/C0eJucjn9dBm-y',
    id: '0226',
    name: 'cable standing crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/XuSVlNUTxqpl+8',
    id: '0874',
    name: 'cable standing crunch (with rope attachment)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/oMv8qlTF0J=dGZ',
    id: '0230',
    name: 'cable standing lift',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/wE00fYSplcrPVM',
    id: '0242',
    name: 'cable tuck reverse crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/jffZP8WavLBDLN',
    id: '0243',
    name: 'cable twist',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/Q7cvDDJZyaoUEX',
    id: '0862',
    name: 'cable twist (up-down)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/56c3xSRLNA_G+4',
    id: '2963',
    name: 'captains chair straight leg raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/NdGTDJDa-K50Dn',
    id: '0260',
    name: 'cocoons',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/xrGITkVER-6sHx',
    id: '1468',
    name: 'crab twist toe touch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/loCrrJHGUUQ+JX',
    id: '0262',
    name: 'cross body crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/zFIC7144Bd4cvB',
    id: '0267',
    name: 'crunch (hands overhead)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'stability ball',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/aqXOre8rNzgEWd',
    id: '0271',
    name: 'crunch (on stability ball)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'stability ball',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/hgRKluGwrqdhdZ',
    id: '0272',
    name: 'crunch (on stability ball, arms straight)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/pQtMflArXi=qq6',
    id: '0274',
    name: 'crunch floor',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/hjLzNoovdwJ7gd',
    id: '3016',
    name: 'curl-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/CMW4PnNPTQZK9R',
    id: '0276',
    name: 'dead bug',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/p-40O01PBeEpJX',
    id: '0277',
    name: 'decline crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/N0OucW8kjkX-FZ',
    id: '0282',
    name: 'decline sit-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'dumbbell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/NvNMdN_zjoFeCg',
    id: '0407',
    name: 'dumbbell side bend',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/LIdPvlSsC-oshC',
    id: '0443',
    name: 'elbow-to-knee',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/4c=JS12P5bbokZ',
    id: '3303',
    name: 'flag',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/HhDuRuu-vk+t_d',
    id: '0456',
    name: 'flexion leg sit up (bent knee)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/G6Nbbfdx=JLWrb',
    id: '0457',
    name: 'flexion leg sit up (straight arm)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/ItlmRLtitxmznJ',
    id: '2429',
    name: 'frog crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/eySKZe9nbeL3sX',
    id: '3301',
    name: 'frog planche',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/9WJTUCxeSu0Cdj',
    id: '3296',
    name: 'front lever',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/xSXsE212n0Kenv',
    id: '0464',
    name: 'front plank with twist',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/psY6l=klTY7Ofx',
    id: '3315',
    name: 'full maltese',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/ggaFp5psv84cCS',
    id: '3299',
    name: 'full planche',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/rC=fJ73ZXT=74k',
    id: '0467',
    name: 'gorilla chin',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/QbY6Whnu-N9-Yh',
    id: '0469',
    name: 'groin crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/0tJ83XwFNm-yQJ',
    id: '3202',
    name: 'half sit-up (male)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/6Kpn+6HkadrarP',
    id: '1764',
    name: 'hanging leg hip raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/3HLY34b8mAs+5N',
    id: '0472',
    name: 'hanging leg raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/4Nso2wjn+IqxoY',
    id: '1761',
    name: 'hanging oblique knee raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/ldU9LBUhxFKAn9',
    id: '0473',
    name: 'hanging pike',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/j3AJf3TWu-K4jI',
    id: '0474',
    name: 'hanging straight leg hip raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/mpwipI85HC_LQD',
    id: '0475',
    name: 'hanging straight leg raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/LM5XqlqzRuJ7Pp',
    id: '0476',
    name: 'hanging straight twisting leg hip raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/-+DTfX=oUABLOy',
    id: '0484',
    name: 'hip raise (bent knee)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/c0jLA-vD+ydczg',
    id: '1471',
    name: 'inchworm',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/Cb7LHwXdY2dizj',
    id: '3698',
    name: 'inchworm v. 2',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/4XDn2DxSmwaD90',
    id: '0491',
    name: 'incline leg hip raise (leg straight)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/kGyFe4eDzShvbf',
    id: '0495',
    name: 'incline twisting sit-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/V=ZArmnS1B=h22',
    id: '0507',
    name: 'jackknife sit-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/LB4yQFcUSJwqgo',
    id: '0508',
    name: 'janda sit-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'kettlebell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/bB5SmIbKz_EM0m',
    id: '0517',
    name: 'kettlebell advanced windmill',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'kettlebell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/VLEpMHU0PVs2gF',
    id: '0524',
    name: 'kettlebell bent press',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'kettlebell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/mNt4TXeUj1EN+k',
    id: '0530',
    name: 'kettlebell double windmill',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'kettlebell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/75XahHGNF+cNwX',
    id: '0532',
    name: 'kettlebell figure 8',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'kettlebell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/7tL6q5qW2amVyY',
    id: '0554',
    name: 'kettlebell windmill',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/wYanZrS9VyYFna',
    id: '3640',
    name: 'knee touch crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/1BaphiZUwLkGWz',
    id: '3239',
    name: 'kneeling plank tap shoulder (male)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/sAy75-p0SPgcN_',
    id: '3419',
    name: 'l-sit on floor',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'barbell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/tyiTsSJki4kaTA',
    id: '0562',
    name: 'landmine 180',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/oA-jCoOu7gj_sw',
    id: '3300',
    name: 'lean planche',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/5HEdPc4_RLvzrE',
    id: '0570',
    name: 'leg pull in flat bench',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'leverage machine',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/OM-wLvbez2G1mo',
    id: '0583',
    name: 'lever kneeling twist',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'leverage machine',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/Cffnzf29kV1k96',
    id: '1452',
    name: 'lever seated crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'leverage machine',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/Vfh8pSG8ZbEmV5',
    id: '0595',
    name: 'lever seated crunch (chest pad)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'leverage machine',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/EXhmgu8bmBALRO',
    id: '3760',
    name: 'lever seated crunch v. 2',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'leverage machine',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/N0YqcMdlV5Izal',
    id: '0600',
    name: 'lever seated leg raise crunch ',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/uQ4M3gqyuRQO+t',
    id: '1688',
    name: 'lunge with twist',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/LRTueF0jk1X6BG',
    id: '2312',
    name: 'lying elbow to knee',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/XBfnjDmPj3uxGF',
    id: '0620',
    name: 'lying leg raise flat bench',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/h8sYMfi9IXWmNQ',
    id: '0865',
    name: 'lying leg-hip raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/b7Gwg7tMb=ACPY',
    id: '0634',
    name: 'negative crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/B4SKZkYM6kD0Sv',
    id: '1495',
    name: 'oblique crunch v. 2',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/+ZIWyhcamBosXf',
    id: '0635',
    name: 'oblique crunches floor',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'medicine ball',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/ioJKrN+N_FNAij',
    id: '0640',
    name: 'one arm slam (with medicine ball)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'weighted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/-p8+9Lh36s=oHv',
    id: '0641',
    name: 'otis up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/d7xVGbUOydBnip',
    id: '3147',
    name: 'pelvic tilt',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/iBen=ViF3Qy6AS',
    id: '1687',
    name: 'posterior step to overhead reach',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/QeWhcZ5=yV414J',
    id: '3119',
    name: 'potty squat',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/PzI1Nvt7ZFgXsr',
    id: '3665',
    name: 'power point plank',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/5BQM11s=hh7JUt',
    id: '3203',
    name: 'prisoner half sit-up (male)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'stability ball',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/f=Flo3YMk=Tci6',
    id: '1707',
    name: 'prone twist on stability ball',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'stability ball',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/NoPZJ9vh-pBPoR',
    id: '0650',
    name: 'pull-in (on stability ball)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/X_nWSRwVTIHwrr',
    id: '0664',
    name: 'push-up to side plank',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/dqfFzsC2aRHLav',
    id: '3201',
    name: 'quarter sit-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/RQjAtAL-6E+8=X',
    id: '0872',
    name: 'reverse crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/p4H+epH4D6apqp',
    id: '3663',
    name: 'reverse plank with leg lift',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'roller',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/wmcITUhJPSlvNI',
    id: '2204',
    name: 'roller body saw',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'roller',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/ypY8ITAh_loYBk',
    id: '2206',
    name: 'roller reverse crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/B9+zjo-4IPY3Tw',
    id: '0687',
    name: 'russian twist',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/Nu7ryJAC0Llypb',
    id: '0689',
    name: 'seated leg raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/NRdpX10IUD1B2f',
    id: '0691',
    name: 'seated side crunch (wall)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/yOeaj9ATQgUw2V',
    id: '3699',
    name: 'shoulder tap',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/D3pUpoXq_2SFtX',
    id: '0705',
    name: 'side bridge v. 2',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/1P3i7mT4sydO_x',
    id: '0709',
    name: 'side hip (on parallel bars)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/Cr2GHAuOtOZOkP',
    id: '3213',
    name: 'side-to-side toe touch (male)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/t79_wn7Dun=Hfa',
    id: '0735',
    name: 'sit-up v. 2',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/MrkIrvZEap+L+c',
    id: '3679',
    name: 'sit-up with arms on chest',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'hammer',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/R7js6A6MBV=q7D',
    id: '1496',
    name: 'sledge hammer',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'smith machine',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/72TOa16XTDuKrW',
    id: '0756',
    name: 'smith hip raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'dumbbell',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/tf7pkNnH-pVM3b',
    id: '0777',
    name: 'spell caster',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/+feTNq4e6fx-KA',
    id: '2329',
    name: 'spine twist',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'stability ball',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/HidxEPA=k=j0oF',
    id: '2297',
    name: 'stability ball crunch (full range hands behind head)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'wheel roller',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/IbONXX_By9EwtI',
    id: '0796',
    name: 'standing wheel rollerout',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/wnUUojRITSInE5',
    id: '3314',
    name: 'straddle maltese',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/Ja2G-eXNdpL1jp',
    id: '3298',
    name: 'straddle planche',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/f+TORZTRb_xwk5',
    id: '0805',
    name: 'suspended abdominal fallout',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/d83otoWqdMtn-K',
    id: '0807',
    name: 'suspended reverse crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/zpPm87d7IM2ov1',
    id: '0871',
    name: 'tuck crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/+c=9ng8JvsD8ed',
    id: '2802',
    name: 'twisted leg raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/agq=eNvq1sGPIq',
    id: '2801',
    name: 'twisted leg raise (female)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/jkORjWm3oGyXNc',
    id: '3420',
    name: 'v-sit on floor',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/L4mbLkOPd+OESq',
    id: '0826',
    name: 'vertical leg raise (on parallel bars)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'weighted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/e6E7EHNw2P3ngU',
    id: '0832',
    name: 'weighted crunch',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'weighted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/=uRtFXYky4V+ML',
    id: '3670',
    name: 'weighted decline sit-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'weighted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/gWU1hzV7dLMMSM',
    id: '2135',
    name: 'weighted front plank',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'weighted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/lmjT6b_VlrUxCi',
    id: '0866',
    name: 'weighted hanging leg-hip raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'weighted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/RiIL1uAX-J2z0s',
    id: '0840',
    name: 'weighted overhead crunch (on stability ball)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'weighted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/LFAwby=EvfcIaN',
    id: '0846',
    name: 'weighted russian twist',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'weighted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/mARHbT5dIbN9HA',
    id: '0845',
    name: 'weighted russian twist (legs up)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'weighted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/bnAgo7Ugji+7bI',
    id: '2371',
    name: 'weighted russian twist v. 2',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'weighted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/sdTjSKAnvNmdsQ',
    id: '0849',
    name: 'weighted seated twist (on stability ball)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'weighted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/oF+A9DNoa3fdb0',
    id: '0850',
    name: 'weighted side bend (on stability ball)',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'wheel roller',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/0R0HEBtpKtFB6i',
    id: '0857',
    name: 'wheel rollerout',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/xbW99x1pDiVniN',
    id: '0858',
    name: 'wind sprints',
    target: 'abs',
  },
];
